"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var auth_types_1 = require("@firebase/auth-types");
exports.EmailAuthProvider = auth_types_1.EmailAuthProvider;
exports.FacebookAuthProvider = auth_types_1.FacebookAuthProvider;
exports.GithubAuthProvider = auth_types_1.GithubAuthProvider;
exports.GoogleAuthProvider = auth_types_1.GoogleAuthProvider;
exports.OAuthProvider = auth_types_1.OAuthProvider;
exports.PhoneAuthProvider = auth_types_1.PhoneAuthProvider;
exports.RecaptchaVerifier = auth_types_1.RecaptchaVerifier;
exports.TwitterAuthProvider = auth_types_1.TwitterAuthProvider;
exports.FirebaseAuth = auth_types_1.FirebaseAuth;
