"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var firestore_types_1 = require("@firebase/firestore-types");
exports.FirebaseFirestore = firestore_types_1.FirebaseFirestore;
exports.GeoPoint = firestore_types_1.GeoPoint;
exports.Blob = firestore_types_1.Blob;
exports.Transaction = firestore_types_1.Transaction;
exports.WriteBatch = firestore_types_1.WriteBatch;
exports.DocumentReference = firestore_types_1.DocumentReference;
exports.DocumentSnapshot = firestore_types_1.DocumentSnapshot;
exports.QueryDocumentSnapshot = firestore_types_1.QueryDocumentSnapshot;
exports.Query = firestore_types_1.Query;
exports.QuerySnapshot = firestore_types_1.QuerySnapshot;
exports.CollectionReference = firestore_types_1.CollectionReference;
exports.FieldValue = firestore_types_1.FieldValue;
exports.FieldPath = firestore_types_1.FieldPath;
